- name : Starting migration
  become: true
  remote_user: ec2-user
  become_method: sudo
  hosts: nodes
  gather_facts: no
  force_handlers: True
  tasks:
  - name: <== Deploy payload ==>
    copy:
      src: "../payloads/start_dd_aws.py"
      dest: "/tmp/start.py"
  - name: <== Setup the environment ==>
    copy:
      src: "../payloads/.env"
      dest: "/tmp/.env"
  - name: <== Executing payload ==>
    shell: "python /tmp/start.py"
    register: st
    become: True
  - name: Message
    debug:
      var: st
