- hosts: all
  gather_facts: true
- name: executing redhat 8 playbook
  import_playbook: aws_env_setup_redhat_8.yaml
  when: ansible_distribution == "Redhat" and ansible_distribution_major_version >= '7'