- name : Setting up migration tool
  become: true
  remote_user: ec2-user
  become_method: sudo
  hosts: tool
  gather_facts: no
  tasks:
  - name: add MongoDB official repository for Redhat
    copy:
      src: "./mongodb.3.6.repo"
      dest: "/etc/yum.repos.d/mongodb-org-3.6.repo"


  - name: Install mongodb
    yum:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Start and enable service
    service:
      name: mongod
      state: started
      enabled: true
